### ISSUE TITLE
Dependency on picu 0.8

### ISSUE THREAD

**Issue by mattias-p** [icann/munidata#1]
I'm having trouble following the instruction to install dependencies.
```
$ pip install -r requirements.txt
Downloading/unpacking picu>=0.8 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement picu>=0.8 (from -r requirements.txt (line 1)) (from versions: 0.5, 0.4, 0.3, 0.6, 0.7)
Cleaning up...
No distributions matching the version for picu>=0.8 (from -r requirements.txt (line 1))
Storing debug log for failure in /home/mattiasp/.pip/pip.log
```
If I lower the requirement to picu>=0.7 things seem to work out fine. Is there some problem with using picu 0.7? If so, where can I find picu 0.8?

**Comment by kjd** [comment]
picu v0.8 is at http://github.com/icann/picu

@wil  — are you responsible for updating PyPI for this?

**Comment by mattias-p** [comment]
Thanks for the quick reply! That link doesn't work for me. I get a 404. Maybe the repo isn't public?

**Comment by kjd** [comment]
You're right. That should now be fixed.

**Comment by mattias-p** [comment]
Now it works. Thanks!

**Comment by wil** [comment]
@kjd - yes, I have now uploaded the current revision as 0.8 to PyPI.
